# The URL the site will be built for
base_url = "https://rudoblog.netlify.com"

compile_sass = true
title = "Rudo's blog"
description = ""
highlight_code = true
generate_feed = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
    {name = "archive", rss = true},
]

[extra]
author = "Rudo"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/archive", name = "Archive"},
]
katex_enable = true
katex_auto_render = true

even_title = "Rudo's blog"
